import "./globals.css";
import { JetBrains_Mono } from "next/font/google";
import RootHeader from "./header";
import localFont from "next/font/local";
const font = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["700", "300", "100"],
});
const local = localFont({
  src: [
    {
      path: "./assets/font/LINESeedKR-Th.woff2",
      weight: "100",
      style: "lighter",
    },
    {
      path: "./assets/font/LINESeedKR-Rg.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/font/LINESeedKR-Bd.woff2",
      weight: "700",
      style: "bolder",
    },
  ],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={local.className}>
        <RootHeader />
        {children}
      </body>
    </html>
  );
}
